package com.example.websocket;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Document(collection = "users")
@Data
public class User {

    @Id
    private String id;
    private String username;
    private String email;
    private String password;
    private List<String> groups = new ArrayList<>(); // Initialize the list
    private String mood;
    private LocalDateTime moodTimestamp;
    private String profilePictureBase64; // Add this line

    // Other getters and setters generated by Lombok
}
